name: 'Push Actor to Apify'
description: 'Push and build an Actor to the Apify platform'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  token:
    description: 'Your Apify token'
    required: true
  actor-id:
    description: 'Name or ID of the Actor to push (e.g. "apify/hello-world" or "E2jjCZBezvAZnX8Rb"). If not provided, the command will create or modify the Actor with the name specified in ".actor/actor.json" file.'
    required: false
    default: ''
  build-tag:
    description: 'Build tag to be applied to the successful Actor build. By default, it is taken from the ".actor/actor.json" file.'
    required: false
    default: ''
  version:
    description: 'Actor version number to which the files should be pushed. By default, it is taken from the ".actor/actor.json" file.'
    required: false
    default: ''
  working-directory:
    description: 'The working directory where the `.actor` folder is located. By default, it is the root of the repository.'
    required: false
    default: ${{ github.workspace }}
runs:
  using: 'composite'
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1
    - name: Set up Apify CLI
      uses: apify/setup-apify-cli-action@v1.0.0
      with:
        token: ${{ inputs.token }}
    - name: Push the Actor
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        push_args=()

        if [ -n "${{ inputs.actor-id }}" ]; then
          push_args+=(${{ inputs.actor-id }})
        fi

        if [ -n "${{ inputs.build-tag }}" ]; then
          push_args+=(--build-tag=${{ inputs.build-tag }})
        fi

        if [ -n "${{ inputs.version }}" ]; then
          push_args+=(--version=${{ inputs.version }})
        fi

        apify push "${push_args[@]}"
